config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resource :user
  resources :users
  get '/users/:id/project_log', to: 'users#project_log', as: 'project_log'
  get '/users/:id/participant_project_log', to: 'users#participant_project_log', as: 'participant_project_log'

  resources :projects
  delete '/projects/:id/delete', to: "projects#destroy", as: 'delete_project'

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :collaboration_requests, only: :index
  resources :projects do
    resources :collaboration_requests, only: [:create, :index]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post '/collaboration_request/:id/accept', to: 'collaboration_requests#accept', as: 'accept_collaboration'
  post '/collaboration_request/:id/decline', to: 'collaboration_requests#decline', as: 'decline_collaboration'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :project_users, dependent: :destroy
  has_many :projects, through: :project_users
  has_many :owned_projects, foreign_key: "owner_id", class_name: "Project"
  has_many :collaboration_requests_as_requester, foreign_key: "requester_id", class_name: "CollaborationRequest"
  has_many :collaboration_requests_on_projects_owned, through: :owned_projects, source: :collaboration_requests
  has_many :collaboration_requests, foreign_key: "requester_id"
  has_one_attached :photo
  validates :first_name, :last_name, :bio, :skill, :tagline, presence: true, on: :update
  # has_many :colloboration_request_demands, foreign_key: "requestee_id", class_name: "CollaborationRequest"

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end


  def education_details
    return unless course && university
    "Studied #{course.capitalize} at #{university.capitalize} from #{uni_start_year} to #{uni_end_year}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render plain: @user.inspect
    else
      render :new
    end
  end

  def index
    @user = User.all
  end

  def project_log
    @user = current_user
  end

  def participant_project_log
    @user = current_user
  end


  def update
    if current_user.update!(user_params)
      flash[:notice] = "Profile successfully updated"
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :tagline,
      :bio,
      :uni_start_year,
      :uni_end_year,
      :course,
      :skill,
      :university
    )
  end
end

app/views/users/edit.html.erb
<div class='container'>
  <%= simple_form_for current_user, url: user_path do |f| %>
    <%= f.input :email %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :tagline %>
    <%= f.input :bio %>
    <%= f.input :date_of_birth %>
    <%= f.input :university%>
    <%= f.input :uni_start_year %>
    <%= f.input :uni_end_year %>
    <%= f.input :course %>
    <%= f.input :skill %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/participant_project_log.html.erb
<div class= "project-log-wrapper">
  <div class= "project-log">
  <h1 class="project-log-header">Collaborative Projects:</h1>
    <% @user.projects.each do |project| %>
    <div class= "project-log-card">
      <h2 class="project-log-name"><%= project.name %></h2>
        <h2 class="project-log-description">Description: </h2>
        <p><%= project.description %></p>
        <div class="chat-section">
            <%= link_to 'View Chat', chatroom_path(project.chatroom), class: "btn btn-lg btn-primary" %>
            </div>
        <h2 class="project-log-collabs">Collaborators:</h2>
          <% project.collaborators.each do |collaboration| %>
          <p class="collab-names"><%= collaboration.first_name %></p>
          <%end %>
        </div>
      <%end %>
  </div>
</div>

app/views/users/project_log.html.erb
<div class= "project-log-wrapper">
  <div class= "project-log">
    <h1 class="project-log-header">Projects I own:</h1>
    <% @user.owned_projects.each do |project| %>
      <div class= "project-log-card">
        <h2 class="project-log-name"><%= project.name %></h2>
        <h2 class="project-log-description">Description: </h2>
        <h3><%= project.description %></h3>
        <div class="chat-section">
            <%= link_to 'View Chat', chatroom_path(project.chatroom), class: "btn btn-lg btn-primary" %>
            </div>
          <h2 class="participant_project-log-collabs">Collaborators:</h2>
          <%project.collaborators.each do |collaboration| %>
          <p class="collab-names"><%= collaboration.full_name %></p>
          <%end %>
        </div>
      <%end %>
    </div>
</div>





<%# <div class = "deleteprojectbutton">
<%= link_to "Delete Project", delete_project_path(current_user), class: "btn btn-lg btn-primary" %>

app/views/users/show.html.erb
<div class="user-show-wrapper">
  <div class="user-show-card">
    <div class="user-show-card-internal">
      <div class="leftcolumn">
        <% if current_user.photo.attached?%>
          <%= cl_image_tag current_user.photo.key, class: "profilepic", id: "p.p" %>
        <% else %>
          <%= image_tag "User_font_awesome.svg.png", class: "profilepic", id: "p.p"%>
        <% end %>
        <h1><%= @user.full_name%></h1>
        <div class="tagline">
          <h3><%=@user.tagline%></h3>
        </div>
        <div class="skills">
          <h3>Skills:</h3>
          <h4><%= @user.skill %></h4>
        </div>
        <div class="qualifications">
          <h3>Qualifications:</h3>
          <h4><%= @user.education_details %></h4>
        </div>
        <div class = "editprofilebutton">
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-lg btn-primary" %>
        </div>
      </div>

      <div class="rightcolumn">
        <div class="bio">
          <h1>Biography:</h1>
          <h3><%= @user.bio %></h3>
        </div>
        <div class = "userstats">
          <h2>Project Log:</h2>
        </div>
        <div class="projectsowned">
          <h3>My Projects:</h3>
        </div>
        <div class= "project-log-wrapper">
          <% @user.owned_projects.each do |project| %>
            <div class= "project-log-card">
              <h2 class="project-log-name"><%= project.name %></h2>
              <h2 class="project-log-description">Description: </h2>
              <p><%= project.description %></p>
              <h2 class="project-log-collabs">Collaborators:</h2>
              <%project.collaborators.each do |collaboration| %>
                <p class="collab-names"><%= collaboration.full_name %></p>
              <%end %>
                  <div class = "collab-pics">
              <% project.collaborators.each do |collaboration| %>
                  <% if collaboration.photo.attached? %>
                    <%= cl_image_tag collaboration.photo.key, class: 'avatar', height: '32px', width: '32px' %>
                  <% else %>
                    <img class="avatar" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
                  <% end %>
                  <% end %>
          </div>
              <div class="chat-section">
                <%= link_to 'View Chat', chatroom_path(project.chatroom), class: "btn btn-primary mr-10", id: "chat-btn" %>
              </div>
            </div>
          <%end %>
        </div>
        <div class="projectsinvolved">
          <h3>Projects I Have Joined:</h3>
        </div>
        <div class= "project-log-wrapper">
          <% @user.projects.each do |project| %>
            <div class= "project-log-card">
              <h2 class="project-log-name"><%= project.name %></h2>
              <h2 class="project-log-description">Description: </h2>
              <p><%= project.description %></p>
              <h2 class="project-log-collabs">Collaborators:</h2>
              <% project.collaborators.each do |collaboration| %>
                <p class="collab-names"><%= collaboration.first_name %></p>
              <%end %>
              <div class = "collab-pics">
              <% project.collaborators.each do |collaboration| %>
                  <% if collaboration.photo.attached? %>
                    <%= cl_image_tag collaboration.photo.key, class: 'avatar' %>
                  <% else %>
                    <img class="avatar" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
                  <% end %>
                  <% end %>
          </div>
              <div class="chat-section">
                <%= link_to 'View Chat', chatroom_path(project.chatroom), class: "btn btn-lg btn-primary" %>
              </div>
            </div>
          <%end %>
        </div>
      </div>
    </div>
  </div>
</div>