config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resource :user
  resources :users
  get '/users/:id/project_log', to: 'users#project_log', as: 'project_log'
  get '/users/:id/participant_project_log', to: 'users#participant_project_log', as: 'participant_project_log'

  resources :projects
  delete '/projects/:id/delete', to: "projects#destroy", as: 'delete_project'

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :collaboration_requests, only: :index
  resources :projects do
    resources :collaboration_requests, only: [:create, :index]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post '/collaboration_request/:id/accept', to: 'collaboration_requests#accept', as: 'accept_collaboration'
  post '/collaboration_request/:id/decline', to: 'collaboration_requests#decline', as: 'decline_collaboration'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- Grid container -->
  <div class="container pt-7 text-center text-white d-flex justify-content-center align-items-center">
    <!-- Section: Social media -->
    <section class="mb-7">
      <!-- Facebook -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">
  <div class="navbar-left">
    <%= link_to "Home", "/", class: "navbar-brand" %>
    <%= link_to "Projects", projects_path, class: "navbar-brand" %>
    <%= link_to "Add Project", new_project_path, class: "navbar-brand" %>
    <%= link_to "Requests", collaboration_requests_path, class: "navbar-brand" %>
    <% if user_signed_in? %>
      <%= link_to "Profile", user_path(current_user), class: "navbar-brand" %>
    <% else %>
      <%# <%= link_to "Sign-in", new_user_session_path %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-right" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <%# <li class="nav-item active">
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item dropdown">
        <% if current_user.photo.attached?%>
        <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "User_font_awesome.svg.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%# <%= link_to "Chat" chatrooms_path, class: "navbar-brand" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "text-white btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>