config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resource :user
  resources :users
  get '/users/:id/project_log', to: 'users#project_log', as: 'project_log'
  get '/users/:id/participant_project_log', to: 'users#participant_project_log', as: 'participant_project_log'

  resources :projects
  delete '/projects/:id/delete', to: "projects#destroy", as: 'delete_project'

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :collaboration_requests, only: :index
  resources :projects do
    resources :collaboration_requests, only: [:create, :index]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post '/collaboration_request/:id/accept', to: 'collaboration_requests#accept', as: 'accept_collaboration'
  post '/collaboration_request/:id/decline', to: 'collaboration_requests#decline', as: 'decline_collaboration'
end

app/models/collaboration_request.rb
class CollaborationRequest < ApplicationRecord
  belongs_to :project
  belongs_to :requester, class_name: "User"
  enum :status, { pending: "pending", accepted: "accepted", declined: "declined" }
  validates :content, length: { minimum: 5 }
end

app/controllers/collaboration_requests_controller.rb
class CollaborationRequestsController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @collaboration_request = CollaborationRequest.new(collaboration_request_params)
    @collaboration_request.requester = current_user
    @collaboration_request.project = @project
    if @collaboration_request.save!
      redirect_to collaboration_requests_path
      flash[:notice] = "Request Sent"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @collaboration_request = CollaborationRequest.new
  end

  def index
  end

  def accept
    @collaboration_request = CollaborationRequest.find(params[:id])
    @collaboration_request.status = "accepted"
    @collaboration_request.save!
    @project_user = ProjectUser.create(project: @collaboration_request.project, user: @collaboration_request.requester)
    redirect_to collaboration_requests_path
  end

  def decline
    @collaboration_request = CollaborationRequest.find(params[:id])
    @collaboration_request.status = "declined"
    @collaboration_request.save!
    redirect_to collaboration_requests_path
  end


# def set_request_status
#   if @collaboration_request.status == "accepted"
#     puts "\e[32m Accepted!"
#   elsif @collaboration_request.status == "declined"
#     puts "\e[31m Declined"
#   else
#     puts "\e[31m Pending"
#   end
# end






  # list the collaboration requests that the project owner has recieved
  # list the collaboration requests that the requestee has made


  private

  def collaboration_request_params
    params.require(:collaboration_request).permit(:content)
  end
end

app/views/collaboration_requests/index.html.erb
<div class= "collab-request-wrapper">
  <div class= "collab-request-card">
    <div class="m-5">
    <h1 class="display-6">Collaboration Requests</h1>

    <h2 class="request-sent">Requests I have sent:</h2>


      <% current_user.collaboration_requests_as_requester.each do |collaboration_request| %>
      <div class="collab-card">
      <h3 class="inside-info">Project name: <%= link_to collaboration_request.project.name, project_path(collaboration_request.project) %></h3>
      <h3 class="inside-info">  Owned by: <%= link_to collaboration_request.project.owner.full_name, user_path(collaboration_request.project.owner) %></h3>
      <h3 class="inside-info">  Status: <%= collaboration_request.status %></h3>
        </div>
      <% end %>


    <h2 class="request-recieved">Requests I have received:</h2>

    <% current_user.collaboration_requests_on_projects_owned.each do |collaboration_request| %>
    <div class="collab-card">
        <h3 class="inside-info">Project name: <%= link_to collaboration_request.project.name, project_path(collaboration_request.project) %></h3>
        <div>
        <h3 class="inside-info"> Requested by: <%= link_to collaboration_request.requester.first_name, user_path(collaboration_request.requester.id)%></h3>
        </div>
        <h3 class="inside-info">Message: <%= collaboration_request.content %></h3>
        <div>
        <h3 class="inside-info">Status: <%= collaboration_request.status%></h3>
        </div>
        <div class="acceptance-card d-flex">
          <div class="accept-btn">
            <%= button_to "Accept", accept_collaboration_path(collaboration_request.id), class: "accept-button", data: { 'turbo-method' => :post }  %>
          </div>
          <div class="decline-btn">
            <%= button_to "Decline", decline_collaboration_path(collaboration_request.id), class: "decline-button", data: { 'turbo-method' => :post }  %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>





<%# status of the request %>
  <%# link to the show of the project the name of the project %>
  <%# link to the show of the project owner %>
  <%# my message %>


<%# <%= link_to user_path(collaborator %>



<%# collaboration requests ive received %>

<%# status of the request %>
<%# link to the show of the project name  %>
<%# link to the show of the requester %>
<%# message of the requester %>
<%# accept/decline buttons %>

<%# Owned by: <%= link_to collaboration_request.project.owner.full_name, user_path(collaboration_request.project.owner)%>
</div>